### ISSUE TITLE
Initial menu missing/sound doesn't immediately play

### ISSUE THREAD

**Issue by jspearman3** [mitjmcc/Seasick#8]
I noticed that in one of the more recent updates (this happened before the new ship models update) that when I clicked play, there would be no sounds until I pressed escape. 

There used to be a start menu at the beginning, but I didn't see it when working on the stat bars/portrait. I'm guessing that has something to do with the sound not immediately working?

**Comment by mitjmcc** [comment]
Deleted a call to pause menu on start up, which fixed it
